FROM python:3.12-slim
LABEL authors="jacktoke"

WORKDIR /opt/airflow

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY ./dashboard ./dashboard

COPY ./dbt/airbnb/receipts.duckdb dbt/airbnb/receipts.duckdb

RUN pip install -r dashboard/requirements.txt